---
- name: Basic run with custom host limit
  hosts: all
  sources:
    - ansible.eda.generic:
        event_delay: 1
        payload:
          - user: "Rick"
            universe: C-137

          - user: "Morty"
            universe: C-137

          - user: "Rick"
            universe: C-132

          - user: "Rick"
            universe: J-19-Zeta-1

          - user: "Beth"
            universe: K-22

          - user: "Jerry"
            universe: C-137
  rules:
    - name: run tests 1
      # condition: event.user == "Rick" and event.universe == "C-137"
      condition: event.universe == "C-137"
      actions:
        - run_playbook: 
            name: "playbook.yml"
        - run_playbook:
            name: "pb-2.yml"
