---
- name: Learning Rules
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 5
  rules:
    # - name: Controller Rule
    #   condition: event.i == 1
    #   action:
    #     # For simple examples just print the event as a debug message.
    #     debug:
    - name: run tests 1
      condition: "event.i == 1"
      actions:
        - run_playbook: 
            name: "pb-1.yml"
        - run_playbook:
            name: "pb-2.yml"
    - name: run tests 2
      condition: "event.i == 1"
      action:
        run_playbook:
          name: "pb-2.yml"
          post_events: false
